language: php
php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2

install:
  - composer install -o -n
  - curl -s -L https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar > coveralls.phar

script:
  - composer run-script test

after_success:
  - php coveralls.phar -v
